workflows:
  android_build:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: 3.44.0
      xcode: 16
      java: 17
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios_build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: 3.44.0
      xcode: 16
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build for simulator
        script: |
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/**/*.app
