platform :ios, '12.0'

# CocoaPods analytics runs network CI to enforce some minimum iOS platform versions.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  File.expand_path('../..', __FILE__)
end

def compute_ios_deployment_target_target_path
  File.join(flutter_root, '.symlinks', 'plugins', 'FlutterPluginIOSNavigator', 'platform')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
